### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by jbmanlol** [cuckydev/PaperPup#1]
I want to see anims in action. also it's not that playable I just want to see 60 fps parappa

**Comment by cuckydev** [comment]
Added compilation instructions to the README, beware that the 3d test stuff is currently disabled as im working on filesystem stuff right now. https://github.com/cuckydev/PaperPup#building

**Comment by jbmanlol** [comment]
do i have to extract the bin and cue files I want to get it working.

**Comment by jbmanlol** [comment]
@cuckydev do I need the bin and cue files?
